### PR TITLE
Fix build with Eigen 3.4

### PR DESCRIPTION
**Pull request by foolnotion**
Hi,

This resolves some compilation errors with Eigen 3.4, the changes are very minor and I am quite confident that they are safe to apply.

Best,
Bogdan

### CODE REVIEW

**Comment by lacava** [comment]
thanks!
